export function editorialPages({S,T,form,hero,wrap}) {
  const images = {
    workshop: {base:'csrad/trainings/biostatistique-atelier',w:1920,h:1280,alt:'Un intervenant anime un atelier de biostatistique devant des participants équipés d’ordinateurs.',caption:'Formation en biostatistique appliquée à la médecine'},
    group: {base:'csrad/trainings/biostatistique-groupe',w:1920,h:1114,alt:'Photo de groupe des participants à la formation en biostatistique, tenant leurs attestations.',caption:'Les participants réunis à l’issue de la formation'},
    participants: {base:'cemcc/events/cemcc-rencontre-participants',w:1920,h:1280,alt:'Participants réunis dans une salle lors d’une rencontre CEMCC.',caption:'Une rencontre de la communauté CEMCC'},
    speaker: {base:'cemcc/events/cemcc-intervention-conference',w:1280,h:1920,alt:'Une intervenante prend la parole au pupitre lors d’une rencontre CEMCC.',caption:'Prise de parole lors d’une rencontre CEMCC'},
    heart: {base:'cemcc/activities/healthy-heart-rencontre',w:1920,h:1280,alt:'Un intervenant s’adresse au public pendant une séance du Healthy Heart Program.',caption:'Healthy Heart Program — un temps de sensibilisation'},
  };
  const escape = (s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function photo(key,{eager=false,caption=true,cls='',sizes='(max-width: 700px) 100vw, 50vw',zoom=false}={}){
    const x=images[key],src=`/images/${x.base}-1280.webp`;
    const img=`<img src="${src}" srcset="/images/${x.base}-640.webp 640w, ${src} 1280w, /images/${x.base}-1920.webp 1920w" sizes="${sizes}" width="${x.w}" height="${x.h}" alt="${x.alt}" loading="${eager?'eager':'lazy'}" decoding="async" ${eager?'fetchpriority="high"':''}>`;
    return `<figure class="editor-photo ${cls}">${zoom?`<button type="button" class="photo-open" data-image="/images/${x.base}-1920.webp" data-caption="${x.caption}" data-alt="${x.alt}" aria-label="Agrandir : ${x.caption}">${img}<span class="zoom-hint" aria-hidden="true">Agrandir ↗</span></button>`:img}${caption?`<figcaption>${x.caption}<span>© CEMCC</span></figcaption>`:''}</figure>`;
  }
  const logo=(cls='')=>`<img class="official-logo ${cls}" src="/images/cemcc/logo/cemcc-logo-compact.webp" width="182" height="320" alt="Logo officiel du Collège d’Étudiants et Médecins Chrétiens Chercheurs" loading="lazy">`;
  const link=(href,text,variant='primary')=>`<a class="btn btn-${variant}" href="${href}">${text} <span aria-hidden="true">↗</span></a>`;
  const ask=(service)=>'/demande-service?service='+encodeURIComponent(service);
  const heading=(k,title,text='')=>`<div class="editor-heading"><span class="kicker">${k}</span><h2>${title}</h2>${text?`<p>${text}</p>`:''}</div>`;
  const offerRows=(entries)=>`<div class="offer-list">${entries.map(x=>`<article class="offer-row"><span class="offer-index">${x[0]}</span><div><h3>${x[1]}</h3><p>${x[2]}</p><small>${x[3]}</small></div><a href="${ask(x[1])}" aria-label="Demander : ${x[1]}">En parler <span aria-hidden="true">↗</span></a></article>`).join('')}</div>`;
  const closing=()=>`<section class="closing"><div class="container"><div><span class="kicker">Votre prochain projet</span><h2>Faisons le point sur votre besoin.</h2><p>Un mémoire, une étude, une formation ou une analyse à préparer ? Échangeons.</p></div>${link('/demande-service','Demander un accompagnement')}</div></section>`;
  const gallery=()=>`<div class="gallery-grid">${['group','speaker','workshop','heart','participants'].map(key=>photo(key,{zoom:true,cls:'gallery-'+key,sizes:'(max-width: 700px) 100vw, (max-width: 1000px) 50vw, 65vw'})).join('')}</div>`;
  const dialog=`<dialog id="photo-dialog" class="photo-dialog" aria-label="Photographie agrandie"><div class="lightbox-top"><span id="photo-count">Photographies CEMCC</span><button type="button" class="lightbox-close" aria-label="Fermer la photographie">Fermer ×</button></div><img id="lightbox-image" alt=""><div class="lightbox-bottom"><button type="button" id="photo-prev" aria-label="Photo précédente">←</button><p id="lightbox-caption"></p><button type="button" id="photo-next" aria-label="Photo suivante">→</button></div></dialog>`;

  return {
    '/':()=>`<section class="human-hero"><div class="hero-copy"><div class="hero-location"><span>À GOMA, EN RDC</span><span>EN PRÉSENTIEL & À DISTANCE</span></div><p class="kicker">CEMCC ASBL / CSRAD</p><h1>Transformez votre recherche en <em>impact.</em></h1><p class="hero-description">Nous accompagnons les étudiants, chercheurs et organisations dans la collecte, l’analyse et l’interprétation de leurs données.</p><div class="hero-cta">${link('/services','Découvrir nos services')}${link('/demande-service','Parlons de votre projet','outline')}</div><p class="hero-note"><span class="gold-rule"></span>Recherche. Formation. Service à la communauté.</p></div><div class="hero-photo">${photo('workshop',{eager:true,caption:false,sizes:'(max-width: 900px) 100vw, 55vw'})}<div class="hero-photo-caption"><span>TRANSMETTRE & APPRENDRE</span><p>La biostatistique, au plus près de la pratique.</p><a href="/formations">Nos formations <span aria-hidden="true">↗</span></a></div></div></section>
    <div class="audience-band"><div class="container"><span>Un appui adapté à votre parcours</span><a href="${ask('Mémoire/TFC/TFE')}">Étudiants & chercheurs ↗</a><a href="/formations">Professionnels de santé ↗</a><a href="/organisations">ONG & institutions ↗</a></div></div>
    ${wrap(`<div class="editor-intro">${heading('Le CSRAD, votre centre de services','Une méthode rigoureuse.<br>Un accompagnement de proximité.')}<div><p>De la question de recherche à la présentation des résultats, nous vous aidons à avancer avec des outils adaptés et des explications claires.</p><a class="text-link" href="/csrad">Découvrir le CSRAD ↗</a></div></div><div class="home-offers">${S.slice(0,3).map(x=>`<a class="home-offer" href="${ask(x[1])}"><span>${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p><b aria-hidden="true">↗</b></a>`).join('')}</div>`)}
    ${wrap(`<div class="editor-split image-first"><div>${photo('group',{cls:'group-photo',sizes:'(max-width: 900px) 100vw, 60vw'})}</div><div class="editor-copy">${heading('Apprendre ensemble','Des formations ancrées dans la pratique.','Biostatistique, SPSS, KoboCollect, Excel : nous partageons des méthodes et des outils utiles pour vos travaux et votre activité professionnelle.')}<p class="small-label">Formation en biostatistique appliquée à la médecine</p>${link('/formations','Explorer les formations')}</div></div>`,'alt')}
    ${wrap(`<div class="editor-split community"><div class="editor-copy">${heading('CEMCC ASBL','La science se construit aussi dans la rencontre.','CEMCC réunit une communauté engagée dans la recherche, la formation et la santé. Les échanges et les actions de sensibilisation prolongent ce travail au service de la communauté.')}<a class="text-link" href="/cemcc">Rencontrer CEMCC ↗</a></div>${photo('participants',{sizes:'(max-width: 900px) 100vw, 50vw'})}</div>`)}
    <section class="community-feature"><div class="container"><div class="editor-split">${photo('heart',{caption:false,sizes:'(max-width: 900px) 100vw, 60vw'})}<div class="editor-copy"><span class="kicker">Santé & communauté</span><h2>Partager les savoirs.<br>Faire vivre la prévention.</h2><p>Le Healthy Heart Program fait partie des activités de sensibilisation de CEMCC. Découvrez les rencontres en images.</p><a class="text-link" href="/realisations">Voir les activités ↗</a></div></div></div></section>
    ${wrap(`<div class="editor-split speaker-story"><div class="portrait-wrap">${photo('speaker',{sizes:'(max-width: 700px) 80vw, 30vw'})}</div><div class="editor-copy">${heading('Dialogue scientifique','Donner une place aux échanges.','Les rencontres CEMCC sont aussi des occasions de prendre la parole, de partager des expériences et d’ouvrir la discussion autour de la santé et de la recherche.')}<a class="text-link" href="/realisations">Parcourir la galerie ↗</a></div></div>`)}${closing()}`,
    '/cemcc':()=>hero('Le Collège','Une communauté pour la recherche et la santé.','Le Collège d’Étudiants et Médecins Chrétiens Chercheurs est une organisation basée à Goma, engagée dans la recherche médicale, la formation et le service à la communauté.')+
      wrap(`<div class="institution-intro"><div class="institution-mark">${logo('institution-logo')}</div><div>${heading('Qui sommes-nous ?','Faire grandir les compétences, partager la connaissance.')}<p>Notre mission est de promouvoir la recherche scientifique, l’innovation et la formation des étudiants et professionnels, et de transformer les résultats scientifiques en solutions utiles pour la communauté.</p></div></div>${photo('participants',{cls:'wide-photo',sizes:'100vw'})}`)+
      wrap(`<div class="editor-split"><div class="editor-copy">${heading('Notre vision','Une recherche utile, portée par des personnes.','Devenir une institution de référence dans la recherche, la formation, l’analyse des données et l’innovation médicale en RDC, puis progressivement en Afrique.')}<div class="values-list">${['Excellence scientifique','Éthique & intégrité','Innovation & collaboration','Responsabilité sociale','Service à la communauté','Valeurs chrétiennes'].map(x=>`<span>${x}</span>`).join('')}</div></div>${photo('speaker',{cls:'institution-portrait',sizes:'(max-width: 700px) 100vw, 40vw'})}</div>`,'alt')+
      wrap(`${heading('Nos axes d’action','Former. Chercher. Sensibiliser.')}<div class="story-pair"><article>${photo('group')}<h3>Développer les compétences en recherche</h3><p>Des formations et échanges autour des outils et des méthodes scientifiques.</p></article><article>${photo('heart')}<h3>Partager les connaissances en santé</h3><p>Des temps de sensibilisation avec la communauté, notamment dans le cadre du Healthy Heart Program.</p></article></div><a class="text-link" href="/realisations">Toutes les photographies d’activités ↗</a>`)+closing(),
    '/csrad':()=>hero('Le centre de services','La rigueur scientifique à vos côtés.','Le Centre de Services en Recherche et Analyse des Données accompagne les étudiants, chercheurs, professionnels et organisations, à Goma et à distance.')+
      wrap(`<div class="editor-split"><div class="editor-copy"><div class="institution-inline">${logo()}<span>Le centre de services<br>de CEMCC ASBL</span></div>${heading('Un accompagnement concret','Clarifier la question.<br>Comprendre les données.','Nous intervenons aux différentes étapes de votre travail : méthodologie, outils de collecte, analyses, interprétation et présentation.')}<p>Pour les travaux académiques, l’accompagnement est pédagogique. Vous restez auteur de votre travail.</p>${link('/demande-service','Décrire mon besoin')}</div>${photo('workshop',{eager:true})}</div>`)+
      wrap(`${heading('Nos champs d’intervention','Un appui selon votre projet.')}${offerRows(S.slice(0,3))}<a class="text-link" href="/services">Tous les services CSRAD ↗</a>`,'alt')+closing(),
    '/a-propos':()=>hero('À propos','La recherche et les données, au service de la communauté.','CEMCC ASBL et son centre de services CSRAD relient formation, accompagnement scientifique et sensibilisation.')+wrap(`<div class="editor-split"><div class="editor-copy">${heading('CEMCC & CSRAD','Une organisation.<br>Un centre de services.')}<p>CEMCC porte la mission institutionnelle et communautaire. Le CSRAD propose un accompagnement méthodologique et technique pour vos projets.</p><div class="hero-cta">${link('/cemcc','CEMCC ASBL')}${link('/csrad','Le CSRAD','light')}</div></div>${photo('participants',{eager:true})}</div><div class="story-pair"><article>${photo('workshop')}<h3>Transmettre des méthodes</h3></article><article>${photo('heart')}<h3>Partager avec la communauté</h3></article></div>`)+closing(),
    '/services':()=>hero('Services CSRAD','Des compétences pour chaque étape de votre recherche.','Accompagnement scientifique, collecte, analyse, formation et communication : une proposition adaptée à votre besoin.')+
      wrap(`<div class="editor-split services-lead">${photo('workshop',{eager:true})}<div class="editor-copy">${heading('Du besoin à la méthode','Nous commençons par vous écouter.','Votre sujet, vos données et vos échéances orientent notre intervention. Nous clarifions ensemble les objectifs et les livrables avant de vous proposer un accompagnement.')}<p class="ethical-note">L’appui académique reste méthodologique et pédagogique : vous construisez et défendez votre propre travail.</p></div></div>${offerRows(S)}`)+
      wrap(`${heading('Comment ça marche ?','Un parcours clair, du premier échange au suivi.')}<ol class="process-list">${['Décrivez votre besoin','Recevez une orientation','Validez une proposition','Travaillez avec notre appui','Recevez vos livrables et le suivi'].map(x=>`<li>${x}</li>`).join('')}</ol>`,'alt')+closing(),
    '/formations':()=>hero('Formations CSRAD','Des outils que l’on apprend à utiliser, ensemble.','Notre équipe propose des formations pratiques en méthodologie, biostatistique et analyse des données.')+
      wrap(`<div class="training-editorial">${photo('group',{eager:true,cls:'training-group',sizes:'(max-width: 900px) 100vw, 65vw'})}<div>${heading('En images','La biostatistique appliquée à la médecine.','Une formation documentée par les photographies CEMCC, du temps de travail aux échanges entre participants.')}${photo('workshop',{cls:'training-small',sizes:'(max-width: 900px) 100vw, 35vw'})}</div></div>`)+
      wrap(`${heading('Choisir son parcours','Les domaines de formation.','Dates, durée, format et tarif vous seront précisés lors de la confirmation de la session.')}<div class="training-list">${T.map((x,i)=>`<article><span class="offer-index">${String(i+1).padStart(2,'0')}</span><div><h3>${x[0]}</h3><p>${x[3]}</p></div><span class="level">${x[1]}</span><a class="register text-link" data-training="${escape(x[0])}" href="#inscription">S’inscrire ↗</a></article>`).join('')}</div>`,'alt')+
      wrap(`<div class="form-shell" id="inscription"><div>${heading('Inscription','Parlons de votre prochaine formation.','Indiquez la formation qui vous intéresse. Nous vous recontactons pour les modalités et la disponibilité.')}</div>${form('training')}</div>`),
    '/realisations':()=>hero('Nos réalisations','Des projets numériques aux rencontres de terrain.','Découvrez MedConnect RDC ainsi qu’une sélection de photographies de nos activités scientifiques, pédagogiques et communautaires.')+
      wrap(`<article class="project-showcase"><div class="project-identity" aria-hidden="true"><span>PROJET NUMÉRIQUE</span><strong>MED<br>CONNECT</strong><b>RDC</b></div><div class="project-copy"><span class="kicker">Application web</span><h2>MedConnect RDC</h2><p>Une application numérique accessible en ligne. Ouvrez MedConnect RDC pour découvrir directement son interface et ses fonctionnalités.</p><a class="btn btn-primary project-link" href="https://medconnect-rdc.lovable.app" target="_blank" rel="noopener noreferrer">Visiter MedConnect RDC <span aria-hidden="true">↗</span></a><small>medconnect-rdc.lovable.app · lien externe</small></div></article>`)+
      wrap(`${heading('Galerie photographique','Former et échanger, en images.','Cliquez sur une photographie pour la voir dans son cadrage complet.')}${gallery()}${dialog}`,'alt')+closing(),
    '/organisations':()=>hero('ONG & institutions','Des données fiables pour orienter vos décisions.','Études, collecte terrain, suivi-évaluation et renforcement des capacités : nous construisons l’intervention selon vos objectifs.')+
      wrap(`<div class="editor-split"><div class="editor-copy">${heading('Renforcer les équipes','Des méthodes partagées.<br>Des résultats compréhensibles.')}<p>Conception d’enquêtes, structuration des bases, analyses et rapports : le CSRAD accompagne les organisations dans la production et la lecture de leurs données.</p>${link(ask('Projet ONG'),'Demander une proposition')}</div>${photo('workshop',{eager:true})}</div>${offerRows([['01','Collecte & contrôle qualité','Conception d’enquêtes, collecte mobile, supervision et structuration des bases.','KoboToolbox, ODK et outils adaptés au terrain.'],['02','Analyse & suivi-évaluation','Études de base, évaluations, analyse et visualisation des données.','Des tableaux et rapports reliés à vos questions.'],['03','Formation des équipes','Renforcer les compétences en collecte, analyse et restitution.','Un contenu adapté aux outils et besoins de votre équipe.']])}`)+closing(),
    '/contact':()=>hero('Contact','Un projet à préparer ?<br>Échangeons.','À Goma ou à distance, nous vous aidons à préciser le service ou la formation qui correspond à votre besoin.')+
      wrap(`<div class="form-shell contact-editorial"><aside><h2>CEMCC ASBL / CSRAD</h2><address>Goma, Nord-Kivu<br>République Démocratique du Congo</address><a class="contact-line" href="https://wa.me/243975121886">WhatsApp · +243 975 121 886 ↗</a><a class="contact-line" href="mailto:cemcc1207@mail.com">cemcc1207@mail.com ↗</a>${photo('participants',{cls:'contact-photo',sizes:'(max-width: 900px) 100vw, 40vw'})}<p class="hint">Pour un règlement Airtel Money, confirmez d’abord votre commande avec un conseiller.</p></aside>${form('contact')}</div>`),
  };
}

export function editorialInteractions(){
  const menu=document.querySelector('#menu'),nav=document.querySelector('#mobile-nav');
  menu?.addEventListener('click',()=>menu.setAttribute('aria-expanded',String(nav.classList.contains('open'))));
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav?.classList.contains('open')){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.focus()}});
  document.querySelectorAll('.nav a,.mobile-nav>a').forEach(a=>{if(new URL(a.href).pathname===location.pathname)a.setAttribute('aria-current','page')});
  const dialog=document.querySelector('#photo-dialog');
  if(!dialog)return;
  const photos=[...document.querySelectorAll('.photo-open')];
  let current=0,previousFocus=null;
  const show=i=>{current=(i+photos.length)%photos.length;const button=photos[current];const img=dialog.querySelector('#lightbox-image');img.src=button.dataset.image;img.alt=button.dataset.alt;dialog.querySelector('#lightbox-caption').textContent=button.dataset.caption;dialog.querySelector('#photo-count').textContent=`Photographie ${current+1} / ${photos.length}`};
  photos.forEach((button,i)=>button.addEventListener('click',()=>{previousFocus=button;show(i);dialog.showModal();document.body.style.overflow='hidden';dialog.querySelector('.lightbox-close').focus()}));
  dialog.querySelector('.lightbox-close').addEventListener('click',()=>dialog.close());
  dialog.querySelector('#photo-prev').addEventListener('click',()=>show(current-1));
  dialog.querySelector('#photo-next').addEventListener('click',()=>show(current+1));
  dialog.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){e.preventDefault();show(current-1)}if(e.key==='ArrowRight'){e.preventDefault();show(current+1)}});
  dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
  dialog.addEventListener('close',()=>{document.body.style.overflow='';previousFocus?.focus()});
}
